import type { BookingService } from "./BookingProvider";

// No prices displayed: everything is quote-based, discussed directly
// with the braider by text at the official number.
export const BOOKING_SERVICES: BookingService[] = [
  {
    id: "boho-knotless",
    category: "Boho",
    name: "Boho Knotless Braids",
    duration: "Duration by length",
    price: "Quote-based",
    description: "Knotless braids with free-flowing curls, the salon's signature. Colors of your choice.",
    img: "/images/femme/boho-knotless-miel.png",
    tag: "Signature",
  },
  {
    id: "knotless",
    category: "Knotless",
    name: "Knotless Braids",
    duration: "Duration by length",
    price: "Quote-based",
    description: "No knot at the root: light, comfortable, and tension-free on your scalp.",
    img: "/images/femme/knotless-braids.png",
    tag: "Popular",
  },
  {
    id: "box-braids",
    category: "Box Braids",
    name: "Box Braids",
    duration: "Duration by length",
    price: "Quote-based",
    description: "The timeless classic: clean square sections, length and thickness of your choice.",
    img: "/images/femme/knotless-longues.png",
  },
  {
    id: "boho-goddess",
    category: "Boho",
    name: "Boho / Goddess Braids",
    duration: "Duration by length",
    price: "Quote-based",
    description: "Bohemian braids with a romantic finish, sprinkled with soft curls.",
    img: "/images/femme/boho-braids.png",
    tag: "Trending",
  },
  {
    id: "goddess-locs",
    category: "Locs",
    name: "Goddess Faux Locs",
    duration: "Duration by length",
    price: "Quote-based",
    description: "The loc look without the commitment: airy, curly, lightweight locs.",
    img: "/images/femme/goddess-locs.png",
  },
  {
    id: "senegalese",
    category: "Twists",
    name: "Senegalese Twists",
    duration: "Duration by length",
    price: "Quote-based",
    description: "Thin, silky, glossy twists. Colored accent strands possible.",
    img: "/images/femme/twists-senegalais.png",
  },
  {
    id: "boho-twists",
    category: "Twists",
    name: "Boho Twists",
    duration: "Duration by length",
    price: "Quote-based",
    description: "Bohemian twists blended with loose curls, from fiery copper to natural black.",
    img: "/images/femme/boho-twists.png",
  },
  {
    id: "micro-braids",
    category: "Box Braids",
    name: "Micro Braids",
    duration: "Duration by length",
    price: "Quote-based",
    description: "Ultra-thin, almost invisible braids. Precision work.",
    img: "/images/femme/micro-braids.png",
  },
  {
    id: "lemonade",
    category: "Cornrows",
    name: "Lemonade / Styled Cornrows",
    duration: "Duration by pattern",
    price: "Quote-based",
    description: "Side-swept or patterned cornrows, with sculpted baby hairs.",
    img: "/images/femme/lemonade-braids.png",
  },
  {
    id: "feed-in",
    category: "Cornrows",
    name: "Feed-in Braids",
    duration: "Duration by pattern",
    price: "Quote-based",
    description: "Cornrows with extensions fed in gradually, natural look from the root.",
    img: "/images/femme/feed-in-braids.png",
  },
  {
    id: "homme-box",
    category: "Men",
    name: "Men's Box Braids",
    duration: "Duration by length",
    price: "Quote-based",
    description: "Clean, well-defined square braids with crisp edges.",
    img: "/images/homme/homme-box-braids.png",
    tag: "Popular",
  },
  {
    id: "homme-box-longues",
    category: "Men",
    name: "Long Box Braids (Men)",
    duration: "Duration by length",
    price: "Quote-based",
    description: "Box braids worn long, with precise sections and a natural fall.",
    img: "/images/homme/homme-box-braids-longues.png",
  },
  {
    id: "homme-twists",
    category: "Men",
    name: "Men's Twists",
    duration: "Duration by volume",
    price: "Quote-based",
    description: "Two-strand twists on natural hair or with extensions.",
    img: "/images/homme/homme-twists.png",
  },
  {
    id: "homme-cornrows-design",
    category: "Men",
    name: "Design Cornrows (Men)",
    duration: "Duration by pattern",
    price: "Quote-based",
    description: "Curved or geometric cornrow patterns, custom-designed.",
    img: "/images/homme/homme-cornrows-design.png",
    tag: "Custom",
  },
  {
    id: "homme-cornrows-natte",
    category: "Men",
    name: "Cornrows with Braid (Men)",
    duration: "Duration by pattern",
    price: "Quote-based",
    description: "Cornrows gathered into a single braid at the back.",
    img: "/images/homme/homme-cornrows-natte.png",
  },
  {
    id: "homme-perles",
    category: "Men",
    name: "Braids & Beads (Men)",
    duration: "Duration by style",
    price: "Quote-based",
    description: "Box braids or twists finished with beads and rings.",
    img: "/images/homme/homme-tresses-perles.png",
  },
  {
    id: "kids",
    category: "Kids",
    name: "Kids' hairstyles",
    duration: "1 – 3 h",
    price: "Quote-based",
    description: "Gentle braids adapted to little ones. Patient, family atmosphere.",
    img: "/images/femme/boho-knotless-noir.png",
  },
  {
    id: "wedding",
    category: "Special",
    name: "Weddings & events",
    duration: "Custom",
    price: "Quote-based",
    description: "Custom hairstyles for your big occasions. Personalized advice.",
    img: "/images/femme/goddess-locs.png",
    tag: "Custom",
  },
];

export const SERVICE_CATEGORIES = [
  "All",
  "Boho",
  "Knotless",
  "Box Braids",
  "Twists",
  "Locs",
  "Cornrows",
  "Men",
  "Kids",
  "Special",
];
